In [7]:
import modern_robotics as mr
import numpy as np
import math

In [8]:
R = np.array([[0, 0, 1],
              [1, 0, 0],
              [0, 1, 0]])
invR = mr.RotInv(R)
print(invR)

[[0 1 0]
 [0 0 1]
 [1 0 0]]


In [9]:
help(mr.NearZero)

Help on function NearZero in module modern_robotics.core:

NearZero(z)
    Determines whether a scalar is small enough to be treated as zero

    :param z: A scalar input to check
    :return: True if z is close to zero, false otherwise

    Example Input:
        z = -1e-7
    Output:
        True



In [10]:
R=np.array([-2,-1,-0.5])
p=mr.VecToso3(R)

In [11]:
p

array([[ 0. ,  0.5, -1. ],
       [-0.5,  0. ,  2. ],
       [ 1. , -2. ,  0. ]])

In [12]:
k=mr.MatrixExp3(p)

In [13]:
k

array([[ 0.60482045,  0.796274  , -0.01182979],
       [ 0.46830057, -0.34361048,  0.81401868],
       [ 0.64411707, -0.49787504, -0.58071821]])

In [14]:
help(mr.ScrewToAxis)

Help on function ScrewToAxis in module modern_robotics.core:

ScrewToAxis(q, s, h)
    Takes a parametric description of a screw axis and converts it to a
    normalized screw axis

    :param q: A point lying on the screw axis
    :param s: A unit vector in the direction of the screw axis
    :param h: The pitch of the screw axis
    :return: A normalized screw axis described by the inputs

    Example Input:
        q = np.array([3, 0, 0])
        s = np.array([0, 0, 1])
        h = 2
    Output:
        np.array([0, 0, 1, 0, -3, 2])



In [15]:
def nearzero(x):
    return print(x<1e-6)

In [16]:
c=nearzero(1e-7)

True


In [17]:
def normalize(x):
    b=math.sqrt(np.dot(x, x))
    #B=math.sqrt(x*x)
    d=x/b
    c=x/np.linalg.norm(x)
    return c

In [18]:
normalize(np.array([1, 2, 3]))

array([0.26726124, 0.53452248, 0.80178373])

In [19]:
def rotInv(R):
    #RT = np.zeros((len(R), len(R)))
    RT=[[0 for _ in range(len(R))] for _ in range(len(R))]
    for a in range (len(R)):
        for b in range(len(R)):
            RT[a][b]=R[b][a]
    RT2 = np.transpose(R)                        
    return RT2


In [20]:
rotInv(np.array([[1, 2, 3],
                 [0, 1, 0],
                 [0, 0, 1]]))

array([[1, 0, 0],
       [2, 1, 0],
       [3, 0, 1]])

In [21]:
def vectoso3(w):
    #w1, w2, w3 = w[0], w[1], w[2]
    return np.array([[0, -w[2], w[1]],
                     [w[2], 0, -w[0]],
                     [-w[1], w[2], 0]]) 

In [22]:
vectoso3(np.array([0,1,2]))

array([[ 0, -2,  1],
       [ 2,  0,  0],
       [-1,  2,  0]])

In [23]:
def so3tovec(W):
    return np.array([-W[1][2],W[0][2],-W[0][1]])

In [24]:
so3tovec(np.array([[ 0, -2,  1],
       [ 2,  0,  0],
       [-1,  0,  0]]))

array([0, 1, 2])

In [25]:
def axisang3(omghattheta):
    omega=normalize(omghattheta)
    theta=np.linalg.norm(omghattheta)
    return (omega,theta)


In [26]:
axisang3(np.array([1,2,3]))

(array([0.26726124, 0.53452248, 0.80178373]), np.float64(3.7416573867739413))

In [27]:
def matrixexp3(so3mat):
    so3vec=so3tovec(so3mat)
    omega=axisang3(so3vec)[0]
    theta=axisang3(so3vec)[1]
    R=np.identity(3)+np.sin(theta)*so3mat+(1-np.cos(theta))*np.dot(so3mat)
    return R

In [28]:
def matrixlog3(R):
    ctheta=(np.trace(R)-1)/2
    if ctheta>=1:
        return np.zeros(3)
    elif ctheta<=-1:
        if not nearzero(1 + R[2][2]):
            omg = (1.0 / np.sqrt(2 * (1 + R[2][2]))) \
                  * np.array([R[0][2], R[1][2], 1 + R[2][2]])
        elif not nearzero(1 + R[1][1]):
            omg = (1.0 / np.sqrt(2 * (1 + R[1][1]))) \
                  * np.array([R[0][1], 1 + R[1][1], R[2][1]])
        else:
            omg = (1.0 / np.sqrt(2 * (1 + R[0][0]))) \
                  * np.array([1 + R[0][0], R[1][0], R[2][0]])
        return vectoso3(np.pi * omg)
    else:
        theta=np.arccos(ctheta)
        omg=(R-R.T)/2*np.sin(theta)
        return (theta*omg)

In [ ]:
#two doubts spherical joint axis of rotation
#and this matrix exponential calculation